// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-ranking-api/ent/ranking"
	"go-ranking-api/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RankingCreate is the builder for creating a Ranking entity.
type RankingCreate struct {
	config
	mutation *RankingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetScore sets the "score" field.
func (rc *RankingCreate) SetScore(i int64) *RankingCreate {
	rc.mutation.SetScore(i)
	return rc
}

// SetCreatedAt sets the "created_at" field.
func (rc *RankingCreate) SetCreatedAt(t time.Time) *RankingCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *RankingCreate) SetNillableCreatedAt(t *time.Time) *RankingCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetUpdatedAt sets the "updated_at" field.
func (rc *RankingCreate) SetUpdatedAt(t time.Time) *RankingCreate {
	rc.mutation.SetUpdatedAt(t)
	return rc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rc *RankingCreate) SetNillableUpdatedAt(t *time.Time) *RankingCreate {
	if t != nil {
		rc.SetUpdatedAt(*t)
	}
	return rc
}

// SetDeletedAt sets the "deleted_at" field.
func (rc *RankingCreate) SetDeletedAt(t time.Time) *RankingCreate {
	rc.mutation.SetDeletedAt(t)
	return rc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (rc *RankingCreate) SetNillableDeletedAt(t *time.Time) *RankingCreate {
	if t != nil {
		rc.SetDeletedAt(*t)
	}
	return rc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (rc *RankingCreate) SetUserID(id int) *RankingCreate {
	rc.mutation.SetUserID(id)
	return rc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (rc *RankingCreate) SetNillableUserID(id *int) *RankingCreate {
	if id != nil {
		rc = rc.SetUserID(*id)
	}
	return rc
}

// SetUser sets the "user" edge to the User entity.
func (rc *RankingCreate) SetUser(u *User) *RankingCreate {
	return rc.SetUserID(u.ID)
}

// Mutation returns the RankingMutation object of the builder.
func (rc *RankingCreate) Mutation() *RankingMutation {
	return rc.mutation
}

// Save creates the Ranking in the database.
func (rc *RankingCreate) Save(ctx context.Context) (*Ranking, error) {
	var (
		err  error
		node *Ranking
	)
	rc.defaults()
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RankingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			if node, err = rc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			if rc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, rc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Ranking)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from RankingMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RankingCreate) SaveX(ctx context.Context) *Ranking {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RankingCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RankingCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RankingCreate) defaults() {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := ranking.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		v := ranking.DefaultUpdatedAt()
		rc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RankingCreate) check() error {
	if _, ok := rc.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "Ranking.score"`)}
	}
	if v, ok := rc.mutation.Score(); ok {
		if err := ranking.ScoreValidator(v); err != nil {
			return &ValidationError{Name: "score", err: fmt.Errorf(`ent: validator failed for field "Ranking.score": %w`, err)}
		}
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Ranking.created_at"`)}
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Ranking.updated_at"`)}
	}
	return nil
}

func (rc *RankingCreate) sqlSave(ctx context.Context) (*Ranking, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (rc *RankingCreate) createSpec() (*Ranking, *sqlgraph.CreateSpec) {
	var (
		_node = &Ranking{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: ranking.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: ranking.FieldID,
			},
		}
	)
	_spec.OnConflict = rc.conflict
	if value, ok := rc.mutation.Score(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: ranking.FieldScore,
		})
		_node.Score = value
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: ranking.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: ranking.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := rc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: ranking.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if nodes := rc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   ranking.UserTable,
			Columns: []string{ranking.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_record = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ranking.Create().
//		SetScore(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RankingUpsert) {
//			SetScore(v+v).
//		}).
//		Exec(ctx)
//
func (rc *RankingCreate) OnConflict(opts ...sql.ConflictOption) *RankingUpsertOne {
	rc.conflict = opts
	return &RankingUpsertOne{
		create: rc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ranking.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (rc *RankingCreate) OnConflictColumns(columns ...string) *RankingUpsertOne {
	rc.conflict = append(rc.conflict, sql.ConflictColumns(columns...))
	return &RankingUpsertOne{
		create: rc,
	}
}

type (
	// RankingUpsertOne is the builder for "upsert"-ing
	//  one Ranking node.
	RankingUpsertOne struct {
		create *RankingCreate
	}

	// RankingUpsert is the "OnConflict" setter.
	RankingUpsert struct {
		*sql.UpdateSet
	}
)

// SetScore sets the "score" field.
func (u *RankingUpsert) SetScore(v int64) *RankingUpsert {
	u.Set(ranking.FieldScore, v)
	return u
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *RankingUpsert) UpdateScore() *RankingUpsert {
	u.SetExcluded(ranking.FieldScore)
	return u
}

// AddScore adds v to the "score" field.
func (u *RankingUpsert) AddScore(v int64) *RankingUpsert {
	u.Add(ranking.FieldScore, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *RankingUpsert) SetCreatedAt(v time.Time) *RankingUpsert {
	u.Set(ranking.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RankingUpsert) UpdateCreatedAt() *RankingUpsert {
	u.SetExcluded(ranking.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RankingUpsert) SetUpdatedAt(v time.Time) *RankingUpsert {
	u.Set(ranking.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RankingUpsert) UpdateUpdatedAt() *RankingUpsert {
	u.SetExcluded(ranking.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RankingUpsert) SetDeletedAt(v time.Time) *RankingUpsert {
	u.Set(ranking.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RankingUpsert) UpdateDeletedAt() *RankingUpsert {
	u.SetExcluded(ranking.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RankingUpsert) ClearDeletedAt() *RankingUpsert {
	u.SetNull(ranking.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Ranking.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *RankingUpsertOne) UpdateNewValues() *RankingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ranking.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Ranking.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *RankingUpsertOne) Ignore() *RankingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RankingUpsertOne) DoNothing() *RankingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RankingCreate.OnConflict
// documentation for more info.
func (u *RankingUpsertOne) Update(set func(*RankingUpsert)) *RankingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RankingUpsert{UpdateSet: update})
	}))
	return u
}

// SetScore sets the "score" field.
func (u *RankingUpsertOne) SetScore(v int64) *RankingUpsertOne {
	return u.Update(func(s *RankingUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *RankingUpsertOne) AddScore(v int64) *RankingUpsertOne {
	return u.Update(func(s *RankingUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *RankingUpsertOne) UpdateScore() *RankingUpsertOne {
	return u.Update(func(s *RankingUpsert) {
		s.UpdateScore()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *RankingUpsertOne) SetCreatedAt(v time.Time) *RankingUpsertOne {
	return u.Update(func(s *RankingUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RankingUpsertOne) UpdateCreatedAt() *RankingUpsertOne {
	return u.Update(func(s *RankingUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RankingUpsertOne) SetUpdatedAt(v time.Time) *RankingUpsertOne {
	return u.Update(func(s *RankingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RankingUpsertOne) UpdateUpdatedAt() *RankingUpsertOne {
	return u.Update(func(s *RankingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RankingUpsertOne) SetDeletedAt(v time.Time) *RankingUpsertOne {
	return u.Update(func(s *RankingUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RankingUpsertOne) UpdateDeletedAt() *RankingUpsertOne {
	return u.Update(func(s *RankingUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RankingUpsertOne) ClearDeletedAt() *RankingUpsertOne {
	return u.Update(func(s *RankingUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *RankingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RankingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RankingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RankingUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RankingUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RankingCreateBulk is the builder for creating many Ranking entities in bulk.
type RankingCreateBulk struct {
	config
	builders []*RankingCreate
	conflict []sql.ConflictOption
}

// Save creates the Ranking entities in the database.
func (rcb *RankingCreateBulk) Save(ctx context.Context) ([]*Ranking, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Ranking, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RankingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RankingCreateBulk) SaveX(ctx context.Context) []*Ranking {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RankingCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RankingCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Ranking.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RankingUpsert) {
//			SetScore(v+v).
//		}).
//		Exec(ctx)
//
func (rcb *RankingCreateBulk) OnConflict(opts ...sql.ConflictOption) *RankingUpsertBulk {
	rcb.conflict = opts
	return &RankingUpsertBulk{
		create: rcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Ranking.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (rcb *RankingCreateBulk) OnConflictColumns(columns ...string) *RankingUpsertBulk {
	rcb.conflict = append(rcb.conflict, sql.ConflictColumns(columns...))
	return &RankingUpsertBulk{
		create: rcb,
	}
}

// RankingUpsertBulk is the builder for "upsert"-ing
// a bulk of Ranking nodes.
type RankingUpsertBulk struct {
	create *RankingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Ranking.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *RankingUpsertBulk) UpdateNewValues() *RankingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ranking.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Ranking.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *RankingUpsertBulk) Ignore() *RankingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RankingUpsertBulk) DoNothing() *RankingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RankingCreateBulk.OnConflict
// documentation for more info.
func (u *RankingUpsertBulk) Update(set func(*RankingUpsert)) *RankingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RankingUpsert{UpdateSet: update})
	}))
	return u
}

// SetScore sets the "score" field.
func (u *RankingUpsertBulk) SetScore(v int64) *RankingUpsertBulk {
	return u.Update(func(s *RankingUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *RankingUpsertBulk) AddScore(v int64) *RankingUpsertBulk {
	return u.Update(func(s *RankingUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *RankingUpsertBulk) UpdateScore() *RankingUpsertBulk {
	return u.Update(func(s *RankingUpsert) {
		s.UpdateScore()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *RankingUpsertBulk) SetCreatedAt(v time.Time) *RankingUpsertBulk {
	return u.Update(func(s *RankingUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RankingUpsertBulk) UpdateCreatedAt() *RankingUpsertBulk {
	return u.Update(func(s *RankingUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RankingUpsertBulk) SetUpdatedAt(v time.Time) *RankingUpsertBulk {
	return u.Update(func(s *RankingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RankingUpsertBulk) UpdateUpdatedAt() *RankingUpsertBulk {
	return u.Update(func(s *RankingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RankingUpsertBulk) SetDeletedAt(v time.Time) *RankingUpsertBulk {
	return u.Update(func(s *RankingUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RankingUpsertBulk) UpdateDeletedAt() *RankingUpsertBulk {
	return u.Update(func(s *RankingUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RankingUpsertBulk) ClearDeletedAt() *RankingUpsertBulk {
	return u.Update(func(s *RankingUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *RankingUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RankingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RankingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RankingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
