// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-ranking-api/ent/ranking"
	"go-ranking-api/ent/schema"
	"go-ranking-api/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	rankingFields := schema.Ranking{}.Fields()
	_ = rankingFields
	// rankingDescScore is the schema descriptor for score field.
	rankingDescScore := rankingFields[0].Descriptor()
	// ranking.ScoreValidator is a validator for the "score" field. It is called by the builders before save.
	ranking.ScoreValidator = rankingDescScore.Validators[0].(func(int64) error)
	// rankingDescCreatedAt is the schema descriptor for created_at field.
	rankingDescCreatedAt := rankingFields[1].Descriptor()
	// ranking.DefaultCreatedAt holds the default value on creation for the created_at field.
	ranking.DefaultCreatedAt = rankingDescCreatedAt.Default.(func() time.Time)
	// rankingDescUpdatedAt is the schema descriptor for updated_at field.
	rankingDescUpdatedAt := rankingFields[2].Descriptor()
	// ranking.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ranking.DefaultUpdatedAt = rankingDescUpdatedAt.Default.(func() time.Time)
	// ranking.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ranking.UpdateDefaultUpdatedAt = rankingDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[2].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[3].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
